services:
  - type: web
    name: my-flask-app
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: flask-db
