"""Final

Revision ID: 1800c7f0b5d9
Revises: 
Create Date: 2025-10-24 16:46:01.622909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1800c7f0b5d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ongs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('ong_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('project_types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=False),
    sa.Column('beneficiaries', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creador_ong_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creador_ong_id'], ['ongs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('organizations', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('monitoring_plan', sa.Text(), nullable=True),
    sa.Column('risk_analysis', sa.Text(), nullable=True),
    sa.Column('success_indicators', sa.Text(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos_colaboracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_requested', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('coverage_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coverage_plan_id'], ['coverage_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compromisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('ong_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('amount_committed', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ong_id'], ['ongs.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_colaboracion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compromisos')
    op.drop_table('pedidos_colaboracion')
    op.drop_table('work_plans')
    op.drop_table('coverage_plans')
    op.drop_table('project_definitions')
    op.drop_table('ongs')
    # ### end Alembic commands ###
